### ISSUE TITLE
Add Gitlab integration

### ISSUE THREAD

**Issue by micheelengronne** [mike-goodwin/owasp-threat-dragon#122]
Is it possible to add Gitlab integration ?

Thanks.

**Comment by jgadsden** [comment]
Hello @micheelengronne 
There is a gitlab integration from a for of TD: 
https://github.com/appsecco/owasp-threat-dragon-gitlab
created by @subashsn . Working at combining this back into TD itself

**Comment by prav10194** [comment]
I have been trying to use gitlab with threat dragon but after logging into gitlab it takes me to the gitlab homepage and not the dashboard. Any idea how to resolve this?

**Comment by jgadsden** [comment]
Hello @prav10194 - at present Threat Dragon does not support gitlab integration, this issue is in place for work to be done on this in future

However there is a fork of Threat Dragon provided by Appsecco that does provide this, if I understand correctly, in a separate repo at:
https://github.com/appsecco/owasp-threat-dragon-gitlab

Can you try this different repo and tell me how you get on? It would be great to have gitlab integration in the main Threat Dragon

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon/issues/9
