### ISSUE TITLE
Content on threatdragon.org

### ISSUE THREAD

**Issue by barbich** [mike-goodwin/owasp-threat-dragon#161]
hello
considering the new home for downloads&code for threat-dragon is on https://github.com/OWASP/threat-dragon it would be helpful to update the relevant content on threatdragon.org (docs, github link,...).

Thanks,

**Comment by jgadsden** [comment]
Hello @barbich - another good point made. I think we may be able to fix up the pages, or possibly create a similar site to threatdragon.org.
@mike-goodwin are you able to help out here?

Thanks, Jon

**Comment by dylanjohnsonsfo** [comment]
Hi Mike

Hope you are keeping well ! We are loving the threat dragon and are
planning to use it across our org in the near future. I was wondering if
you would be up for doing a hangouts to give folks an overview on what it
is, why it's useful and  why you created it, plus how they can
contribute to it ? I think it's great and would love to help you promote
it, if that is something you are interested in.

Thanks

Dylan

**Comment by jgadsden** [comment]
Hello @dylanjohnsonsfo - agreed that @mike-goodwin is the go-to guy when it comes to Threat Dragon, he leads the project and wrote all the code.

If it helps Mike recently did a lightning demo recorded during the OWASP Open Security Summit in June 2020:
https://youtu.be/n6JGcZGFq5o

There was also an OWASP podcast mid this year ... I can look out the link for that if you would like ?

Cheers,
Jon

**Comment by jgadsden** [comment]
Hello @barbich - to update threatdragon.org (including docs.threatdragon.org) requires @mike-goodwin as owner of this repo. Since the move to the OWASP area we are increasing the number of people who have permissions on this sort of thing, so a new docs area has been created to provide threatdragon.github.io . The links in the 3 repos have been updated to point to this site - so this will be in the next release. Also updated the OWASP page to point to the new docs page.

@mike-goodwin the new repo is at https://github.com/threatdragon/threatdragon.github.io and you should have permissions for it along with @andk123 

Cheers, 
Jon
