### ISSUE TITLE
github oauth: too much of requested permissions

### ISSUE THREAD

**Issue by fadeevab** [mike-goodwin/owasp-threat-dragon#72]
To use the online version of application the GitHub's authentication is requested.

However a requested **scope** of permissions is quietly wide:

> This application will be able to **read** and **write** all public repository data. This includes the following:
> 
>     Code
>     Issues
>     Pull requests
>     Wikis
>     Settings
>     Webhooks and services
>     Deploy keys

I'm pretty sure it's enough to get an **empty scope** (see https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/): to read public account information. It's not clear about all other permissions.

Thank you!

**Comment by StephenOTT** [comment]
+1 on this.  WAYYY to much access is being requested

**Comment by mike-goodwin** [comment]
Thanks for your interest in Threat Dragon. I know what you mean about the scope. The problem is that the app wants to write to the repo to store the model files and [GitHub scopes](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes) don't allow anything less than `repo` access as far as I can see.

This was one of the main reasons for creating the [desktop variant](https://github.com/mike-goodwin/owasp-threat-dragon-desktop). Would that be of interest?

**Comment by whereswaldon** [comment]
I think getting a read-write deploy key for the repo would be sufficient. That would only allow access to repo files, but not any of the settings/metatdata/issues/etc.

**Comment by jgadsden** [comment]
This is linked to a similar issue #148 , because  of the scopes available in github this has become a documentation issue

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon/issues/5
